services:
  # The PostgreSQL Database Service
  db:
    image: postgres:17.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  # The Django Web App Service
  webapp:
    build: 
      context: ./webapp
      dockerfile: Dockerfile
    command: uv run python webapp/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./webapp:/app/webapp
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY} 
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
    depends_on:
      - db

  # The Scraper Service
  scrapers:
    build:
      context: ./src
      dockerfile: Dockerfile
    env_file: ".env"
    environment:
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
    depends_on:
      - db
    volumes:
      # Mount source for development (optional)
      - ./src:/home/dockie/src:ro
    # Default command shows help - override to run specific scrapers
    command: ["uv", "run", "python", "-m", "src.scrapers.main", "--help"]

  # Quick test aliases for development
  test-idealo:
    extends: scrapers
    command: ["uv", "run", "python", "-m", "src.scrapers.main", "--platform", "idealo"]
    
  test-ebay:
    extends: scrapers  
    command: ["uv", "run", "python", "-m", "src.scrapers.main", "--platform", "ebay", "--query", "gaming laptop"]

volumes:
  postgres_data: