# Generated by Django 5.2.5 on 2025-09-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_board', '0005_add_last_ebay_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaylisting',
            name='is_best_match',
            field=models.BooleanField(default=False, help_text="Whether listing was in eBay's best match section."),
        ),
        migrations.AddField(
            model_name='product',
            name='is_profitable',
            field=models.BooleanField(default=False, help_text='Whether the product is profitable (potential_profit >= 50€).'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_ebay_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price found on eBay.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='potential_profit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Potential profit (min_ebay_price - idealo_price).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='profit_percentage',
            field=models.FloatField(blank=True, help_text='Profit margin as percentage.', null=True),
        ),
    ]
